[env]
'_'.file = '.env'

[tools]
node = "21.7.3"
goreleaser = "1.24.0"
pre-commit = "3.7.0"
shellcheck = "0.10.0"
"go:github.com/spf13/cobra-cli" = "1.3.0"
"npm:prettier" = "3.2.5"
"npm:scaffdog" = "3.0.0"

[tasks.setup]
description = "Setup (Runs all `setup:*` tasks)"
depends = ["setup:mise", "setup:go-mod"]
run = "mise run setup:pre-commit"

[tasks."setup:mise"]
description = "Install dev dependencies with mise"
run = "mise install -y"

[tasks."setup:go-mod"]
description = "Install go modules with go.mod"
run = "go mod download"

[tasks."setup:pre-commit"]
description = "Sets up pre-commit hooks"
depends = ["setup:mise"]
run = "pre-commit install"

[tasks.build]
description = "Build the CLI application"
alias = "b"
run = "make"
sources = ["go.mod", "main.go", "cmd/**/*.go", "internal/**/*.go"]
outputs = ["bin/app"]

[tasks.release]
description = "Build release binaries"
alias = "r"
run = "goreleaser release --snapshot --rm-dist"
